name: Release
on:
  release:
    types: [created]
jobs:
  example:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # - { runner: macos-latest,  os: darwin,  arch: amd64 }
          - { runner: macos-latest,  os: darwin,  arch: arm64 }
          - { runner: ubuntu-latest, os: linux,   arch: amd64 }
          - { runner: ubuntu-latest, os: windows, arch: amd64 }
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/actions-reproducible-build@main
        with:
          product_name: example-app
          product_version: 1.0.0
          go_version: 1.18
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          instructions: |-
            cd ./testdata/example-app
            go build -o "$BIN_PATH" -trimpath -buildvcs=false
