name: Release
  release:
    types: [created]
jobs:
  example:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # - { runner: macos-latest,  os: darwin,  arch: amd64 }
          - { runner: macos-latest,  os: darwin,  arch: arm64 }
          - { runner: ubuntu-latest, os: linux,   arch: amd64 }
          - { runner: ubuntu-latest, os: windows, arch: amd64 }
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.29
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.18
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
